aws_region              = "ap-southeast-2"
availability_zones      = ["ap-southeast-2a", "ap-southeast-2b"]
vpc_cidr                = "10.0.0.0/16"
public_subnets_cidrs    = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets_cidrs   = ["10.0.101.0/24", "10.0.102.0/24"]
bastion_allowed_cidr    = "0.0.0.0/0"
bastion_instance_type   = "t2.micro"
key_name                = "simo-key"
rds_allowed_cidr_blocks = ["10.0.0.0/16"]
rds_allocated_storage   = 20
rds_engine_version      = "17.4"
rds_instance_class      = "db.t4g.micro"
rds_db_name             = "simonluludb"
rds_username            = "simolulu"
rds_password            = "spoonfest618"
